### ISSUE TITLE
Sound is a problem

### ISSUE THREAD

**Issue by Zygus42** [Corail31/scanner#1]
Your scanner makes almost the identical sound to flapping dragons in the iceandfire mod, which is your only danger signal that you're about to be eaten.  And it's very loud and doesn't change when it finds something.  May I suggest finding some sound files to do with geiger counters, like this one from the geiger wiki: https://upload.wikimedia.org/wikipedia/commons/3/37/Geiger_panic.ogg, although it has to be said, that that is also very loud and annoying :)

**Comment by Corail31** [comment]
there 's a trouble with sounds in the scanner that i haven't seen before, but i'll try your sounds (because it's often annoying), and patch this soon too.
