### ISSUE TITLE
[1.0.1 for 1.11.2] ftb utilities issue

### ISSUE THREAD

**Issue by kreezxil** [Corail31/scanner#2]
Something about your mod doesn't play well with ftb utilities. 

https://github.com/LatvianModder/FTBUtilities/issues/566

I posted first at FTB Utilities, and through a bit of deduction, for instance only your mod provided the scanner command, i removed your mod and FTB Utilities stopped causing the aberrant behavior.

**Comment by Corail31** [comment]
Hi Kreezxil,
this mod is in beta since avril (and haven't been updated since)
i also think it's about the command scanner that was provide as example of beta ^^
