### ISSUE TITLE
Request - Hunt blocks that have not been seen

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/scanner#4]
Self explainitory

**Comment by Corail31** [comment]
Hi P3rf3ct ;)
Could you explain me exactly the request ? :)
Is it about showing blocks on a larger angle of view ?

**Comment by P3rf3ctXZer0** [comment]
Okay so sometimes you need a block you havent found yet - I want to use the scanner to find a block that I have not discovered yet... like for example Titanium even though I had no titanium. Also maybe I want to look for the nearest enchantment table - so now I can see if there are any nearby. Like sniffer but with survival elements.

**Comment by P3rf3ctXZer0** [comment]
I want a scenter style mod but without pure cheating XD

**Comment by P3rf3ctXZer0** [comment]
... not sure I know how to explain everything.

**Comment by Corail31** [comment]
I'll probably add a feature in the future to remember a list of blocks in the scanner instead of only one, perhaps with a radial menu.

**Comment by P3rf3ctXZer0** [comment]
The only thing I suggest due to mod blocks something that hooks into JEI

**Comment by Corail31** [comment]
Scanner is already using oredict, so modded blocks too, but i understand you want to scan a block you never discover by interracting from jei or creative tab, i keep it in mind.

**Comment by P3rf3ctXZer0** [comment]
ty :)
