### ISSUE TITLE
Request - Hunt Biomes

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/scanner#5]
Self Explanatory

**Comment by Corail31** [comment]
I found a mod called NaturesCompass that seems to do it perfectly for biome ;)

**Comment by P3rf3ctXZer0** [comment]
It needs to be updated as using it crashes with latest forge.

**Comment by Corail31** [comment]
Wait for an update of this mod, it will be probably fixed soon ;)
The search for a biome should be a compass to target the direction.
The scanner is used to find multiple blocks in a medium range.
